---
- name: SDN BGP Daemon Remediation Rulebook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        paths:
          - /webhook/sdn-bgp-daemon
        # Optional token authentication (set via env var)
        # token: "{{ lookup('env', 'EDA_WEBHOOK_TOKEN') }}"

  rules:
    - name: Process SDN BGP Daemon Down Alert
      # Alertmanager sends labels under commonLabels and alerts[0].labels
      # Use a single expression (no list) to avoid parser errors
      condition: >
        event.commonLabels.alertname == "SDNBGPDaemonDown"
        and event.commonLabels.component == "bgp"
      action:
        run_job_template:
          name: "SDN BGP Daemon Remediation"
          organization: "Default"
          inventory: "SDN Nodes Inventory"
          extra_vars:
            node_name: "{{ event.commonLabels.node | default(event.alerts[0].labels.node | default(event.alerts[0].annotations.eda_node)) }}"
            alert_name: "{{ event.commonLabels.alertname | default(event.alerts[0].labels.alertname) }}"
            severity: "{{ event.commonLabels.severity | default(event.alerts[0].labels.severity) }}"
            eda_action: "{{ event.alerts[0].annotations.eda_action | default('remediate_bgp') }}"
            eda_playbook: "{{ event.alerts[0].annotations.eda_playbook | default('restart-frr-bgp-agent.yml') }}"
