---
- name: SDN BGP Daemon Remediation Rulebook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        paths:
          - /webhook/sdn-bgp-daemon
        # Optional token authentication (set via env var)
        # token: "{{ lookup('env', 'EDA_WEBHOOK_TOKEN') }}"

  rules:
    - name: Process SDN BGP Daemon Down Alert
      # EDA 2.5 requires a single expression (no list) for condition
      # This handles both alertname variants seen in logs
      condition: (event.alertname == "SDNBGPDaemonDown" or event.alertname == "SDNFRRBGPDaemonDown") and event.labels.component == "bgp"
      action:
        run_job_template:
          name: "SDN BGP Daemon Remediation"
          organization: "Default"
          inventory: "SDN Nodes Inventory"
          extra_vars:
            node_name: "{{ event.labels.node | default(event.commonLabels.node | default(event.alerts[0].labels.node | default(event.alerts[0].annotations.eda_node))) }}"
            alert_name: "{{ event.alertname | default(event.commonLabels.alertname | default(event.alerts[0].labels.alertname)) }}"
            severity: "{{ event.labels.severity | default(event.commonLabels.severity | default(event.alerts[0].labels.severity)) }}"
            eda_action: "{{ event.annotations.eda_action | default(event.alerts[0].annotations.eda_action | default('remediate_bgp')) }}"
            eda_playbook: "{{ event.annotations.eda_playbook | default(event.alerts[0].annotations.eda_playbook | default('restart-frr-bgp-agent.yml')) }}"
