---
- name: SDN BGP Daemon Remediation Rulebook (AAP 2.5 safe)
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        paths:
          - /webhook/sdn-bgp-daemon
        # Optional token authentication (set via env var)
        # token: "{{ lookup('env', 'EDA_WEBHOOK_TOKEN') }}"

  rules:
    - name: Process SDN BGP Daemon Down Alert
      # AAP 2.5: event is wrapped under event.payload (Alertmanager default payload)
      # Single string expression required
      condition: '(event.payload.commonLabels.alertname == "SDNBGPDaemonDown" or event.payload.commonLabels.alertname == "SDNFRRBGPDaemonDown") and event.payload.commonLabels.component == "bgp"'
      action:
        run_job_template:
          name: "SDN-MONITOR-REMEDIATE-TEMPLATE"
          organization: "mcn-infra"
          inventory: "sdn-monitor-remediate-inventory"
          extra_vars:
            node_name: "{{ event.payload.commonLabels.node | default(event.payload.commonAnnotations.eda_node) }}"
            alert_name: "{{ event.payload.commonLabels.alertname }}"
            severity: "{{ event.payload.commonLabels.severity | default('critical') }}"
            eda_action: "{{ event.payload.commonAnnotations.eda_action | default('remediate_bgp') }}"
            eda_playbook: "{{ event.payload.commonAnnotations.eda_playbook | default('restart-frr-bgp-agent.yml') }}"
